######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 29 15:41:42 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += T3.cpp
