######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 1 22:00:39 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dockwindow.h globj.h mainwindow.h slidersgroup.h window.h
SOURCES += dockwindow.cpp globj.cpp globj_2.cpp main.cpp slidersgroup.cpp
QT += opengl
