

/*
 *
 *
 */
#include "local_const.h"


const short int job_table_column_length [] = {
	JOB_TABLE_JOB_ID_LENGTH,			//		10,   0th field of job table
	JOB_TABLE_JOB_TYPE_LENGTH,			//		40,   1
	JOB_TABLE_JOB_TITLE_LENGTH,			//		50,   2
	JOB_TABLE_SPECIALIZATION_LENGTH,	//		50,   3
	JOB_TABLE_COUNTRY_CODE_LENGTH+1,	//		3,    4,  precision of country_code field
	JOB_TABLE_REGION_NAME_LENGTH,		//		30,   5
	JOB_TABLE_STATE_NAME_LENGTH,		//		20,   6
	JOB_TABLE_LOCATION_LENGTH,			//		30,   7
	JOB_TABLE_MIN_SALARY_LENGTH+1,		//		9,    8,  precision of salary field
	JOB_TABLE_MAX_SALARY_LENGTH+1,		//		9,    9,  precision of salary field
	JOB_TABLE_COMPANY_NAME_LENGTH,		//		50,   10
	JOB_TABLE_START_DATE_LENGTH,		//		20,   11
	JOB_TABLE_REFERENCE_NUMBER_LENGTH,	//		30,   12
	JOB_TABLE_CONTACT_PERSON_LENGTH,	//		50,   13
	JOB_TABLE_DESCRIPTION_LENGTH,		//		4000, 14
	JOB_TABLE_QUALIFICATION_LENGTH		//		1000, 15
};


const short int member_table_column_length [] = {
	MEMBER_TABLE_LOGIN_ID_LENGTH,				//	20,  0th
	MEMBER_TABLE_FIRST_NAME_LENGTH,				//	20
	MEMBER_TABLE_MID_I_NAME_LENGTH,				//	20
	MEMBER_TABLE_LAST_NAME_LENGTH,				//	20
	MEMBER_TABLE_SPECIALIZATION_LENGTH,			//	50
	MEMBER_TABLE_EMAIL_LENGTH,					//	50
	MEMBER_TABLE_PHONE_LENGTH,					//	20
	MEMBER_TABLE_FAX_LENGTH,					//	20
	MEMBER_TABLE_WEB_URL_LENGTH,				//	50
	MEMBER_TABLE_CURRENT_COMPANY_LENGTH,		//	30
	MEMBER_TABLE_CURRENT_JOB_TITLE_LENGTH,		//	30
	MEMBER_TABLE_CURRENT_JOB_LOCATION_LENGTH,	//	30
	MEMBER_TABLE_CURRENT_JOB_LOCATION_CODE,		//	1
	MEMBER_TABLE_YEAR_OF_EXP_LENGTH,			//	2
	MEMBER_TABLE_DEGREE_LENGTH,					//	1
	MEMBER_TABLE_JOB_1_LENGTH,					//	50
	MEMBER_TABLE_JOB_2_LENGTH,					//	50
	MEMBER_TABLE_JOB_3_LENGTH,					//	50
	MEMBER_TABLE_DESIRED_SALARY_LENGTH,			//	9		// Precision of int
	MEMBER_TABLE_DESIRED_JOB_LOCATION_LENGTH,		//	30
	MEMBER_TABLE_DESIRED_JOB_LOCATION_CODE_LENGTH,	//	1		// 1: region; 2: state; 3: city
	MEMBER_TABLE_SPECIAL_TALENTS_LENGTH,		//	50
	MEMBER_TABLE_RESUME_LENGTH					//	8000

};

const short int c_g_table_column_length [] = {
	C_G_TABLE_LOGIN_ID_LENGTH,					//	20,  0th
	C_G_TABLE_FIRST_NAME_LENGTH,				//	20
	C_G_TABLE_MID_I_NAME_LENGTH,				//	20
	C_G_TABLE_LAST_NAME_LENGTH,					//	20
	C_G_TABLE_MAJOR_LENGTH,						//	50
	C_G_TABLE_EMAIL_LENGTH,						//	50
	C_G_TABLE_PHONE_LENGTH,						//	20
	C_G_TABLE_FAX_LENGTH,						//	20
	C_G_TABLE_WEB_URL_LENGTH,					//	50
	C_G_TABLE_COLLEGE_NAME_LENGTH,				//	30
	C_G_TABLE_COLLEGE_CITY_LENGTH,				//	30
	C_G_TABLE_COLLEGE_STATE_LENGTH,				//	30
	C_G_TABLE_EXPECTED_DEGREE_LENGTH,			//	1
	C_G_TABLE_EXPECTED_DEGREE_DATE_LENGTH,		//	10
	C_G_TABLE_EXPECTED_MIN_SALARY_LENGTH,		//	9		// Precision of int
	C_G_TABLE_DESIRED_JOB_LOCATION_LENGTH,		//	30
	C_G_TABLE_DESIRED_JOB_LOCATION_CODE_LENGTH,	//	1		// 1: region; 2: state; 3: city
	C_G_TABLE_SPECIAL_TALENTS_LENGTH,			//	50
	C_G_TABLE_RESUME_LENGTH						//	4000

};
