######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 1 00:03:12 2012
######################################################################

QT += opengl
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += globj.h mainwindow.h
SOURCES += globj.cpp main.cpp mainwindow.cpp
