######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 18 23:14:54 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += globj.h mainwindow.h
SOURCES += globj.cpp main.cpp mainwindow.cpp
QT += opengl
