######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 29 16:47:54 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cannonfield.h lcdrange.h
SOURCES += cannonfield.cpp lcdrange.cpp T8.cpp
