######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 29 16:01:23 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += T6.cpp
