######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 29 15:38:13 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += T2.cpp
