######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 29 15:45:24 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += T4.cpp
