######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 29 15:25:50 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += T1.cpp
